server:
  port: 8010
logging:
  level: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: consumer-movie

