server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
security:
  basic:
    enabled: true
  user:
    name:  root
    password: root